site_name: Gustav Wetterlind
site_url: https://www.gwetterlind.com

theme:
  name: material
  palette:
   primary: purple
   accent: blue

  features:
  - navigation.indexes
  - navigation.tabs
  - navigation.top

plugins:
  - search
  - awesome-pages
  - privacy:
      enabled: !ENV [CI, false] #Docs: https://squidfunk.github.io/mkdocs-material/plugins/privacy/
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_date