name: Build and Deploy
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      # - run: pip install mkdocs-rss-plugin
      - run: pip install -U mkdocs-mermaid2-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-awesome-pages-plugin


      - name: Build and Deploy Docs
        run: |
          cd wett
          mkdocs build --site-dir ../site
      
      # Important for when using a Custom Domain
      - name: Copy CNAME to site directory
        run: cp CNAME site/CNAME
      
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git branch -f gh-pages || git checkout -b gh-pages  # Ensure gh-pages branch exists
          git checkout gh-pages
          mv site $RUNNER_TEMP/site  # Temporarily move site directory
          git rm -rf .  # Remove all existing files
          cp -r $RUNNER_TEMP/site/* .  # Copy the built site files to the root of gh-pages branch
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages